version: "3.9"
services:
  besbox-brain:
    image: ghcr.io/andy2great/besbox-brain:latest
    privileged: true
    build:
      context: ./
      dockerfile: apps/brain/Dockerfile
    ports:
      - 8080:80
    networks:
      - besbox_network

  besbox-mouth:
    image: ghcr.io/andy2great/besbox-mouth:latest
    privileged: true
    volumes:
      - /home/ubuntu/pipes:/hostpipe
    build:
      context: ./
      dockerfile: apps/mouth/Dockerfile
    networks:
      - besbox_network

  besbox-ears:
    image: ghcr.io/andy2great/besbox-ears:latest
    privileged: true
    build:
      context: ./
      dockerfile: apps/ears/Dockerfile
    networks:
      - besbox_network

  besbox-version:
    image: ghcr.io/andy2great/besbox-version:latest
    build:
      context: ./
      dockerfile: apps/version/Dockerfile
    ports:
      - 80:80
    networks:
      - besbox_network

networks:
  besbox_network:
    name: besbox_network
    driver: bridge