FROM --platform=$BUILDPLATFORM rust:1-buster AS builder

COPY . .
RUN cargo build --release

FROM arm32v7/rust:1.63 as runner

copy --from=builder ./target/release/besbox ./target/release/besbox
ENV VERSION=0.0.1

CMD ["./target/release/besbox"]