name: besbox-mouth
on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: 'Build:checkout'
        uses: actions/checkout@v2

      - name: 'login'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - id: check_nx_apps
        uses: ignition-is-go/action-nx-affected-apps
        with:
          head: 'origin/main'
          base: github.sha
  
      - name: check app has changed
        if: contains(steps.check_nx_apps.affected_apps, 'version')
        run: exit 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./apps/mouth/Dockerfile
          push: true
          tags: ghcr.io/andy2great/besbox-mouth:latest
          platforms: linux/amd64