name: besbox-version
on:
  push:
    branches:
      - 'main'
env:
  BEFORE_SHA: ${{ github.event.before }}
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: 'Build:checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'login'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm i --ignore-scripts

      - id: check_nx_apps
        run: echo "::set-output name=affected_app::$(npx nx affected:apps --target=main --base=$BEFORE_SHA)"

      - run: echo $(steps.check_nx_apps.outputs.affected_app)

      - name: check app has changed
        if: false == contains(steps.check_nx_apps.outputs.affected_app, 'version')
        run: exit 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./apps/version/Dockerfile
          push: true
          tags: ghcr.io/andy2great/besbox-version:latest
          platforms: linux/amd64