name: besbox-ears
on:
  push:
    branches:
      - 'main'
env:
  BEFORE_SHA: ${{ github.event.before }}
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: 'Build:checkout'
        uses: actions/checkout@v2

      - name: 'login'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm i --ignore-scripts

      - id: check_nx_apps
        run: npx nx affected:apps --target=main --base=$BEFORE_SHA
  
      - name: check app has changed
        if: false == contains(steps.check_nx_apps.affected_apps, 'ears')
        run: exit 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./apps/ears/Dockerfile
          push: true
          tags: ghcr.io/andy2great/besbox-ears:latest
          platforms: linux/amd64