name: besbox-version
on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: 'Build:checkout'
        uses: actions/checkout@v2

      - name: 'login'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: nrwl/nx-set-shas@v3

      - id: check_nx_apps
        run: npx nx affected --target=apps --base=main
  
      - name: check app has changed
        if: contains(steps.check_nx_apps.affected_apps, 'version')
        run: exit 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./apps/version/Dockerfile
          push: true
          tags: ghcr.io/andy2great/besbox-version:latest
          platforms: linux/amd64